### ISSUE TITLE
[BUG] - repetition or wrong transcripions on many calls

### ISSUE THREAD

**Issue by Sharrnah** [Sharrnah/whispering#10]
Seems there is an issue with the newest CTranslate2 / faster-whisper library that can result in repetions or completely wrong or missing transcribtions like resulting in `!!!!!!!!!!!!!!!!!!!!!!!!` or `.   %   `.

https://github.com/guillaumekln/faster-whisper/issues/79

(needs more investigation)

**Comment by Infinitay** [comment]
Am I correct in saying that the latest version of faster-whisper (3.10.3) fixed it?

**Comment by Sharrnah** [comment]
in my testings, it seems it has fixed it.
Will push an update today.

**Comment by Sharrnah** [comment]
New update is out. So i will close this.
